Console.Write("Enter Number 1: ");
string Number1 = Console.ReadLine();
int N1 = int.Parse(Number1);
Console.Write("Enter Number 2: ");
string Number2 = Console.ReadLine();
int N2 = int.Parse(Number2);
Console.Write("Enter Number 3: ");
string Number3 = Console.ReadLine();
int N3 = int.Parse(Number3);
int max = N1;
if(N2>max) max=N2;
if(N3>max) max=N3;
Console.WriteLine(max);